# Generated by Django 4.2.7 on 2024-01-31 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("period", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField()),
                ("value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("color", models.CharField(max_length=6)),
                (
                    "budget_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="period.period"
                    ),
                ),
            ],
        ),
    ]
