# Generated by Django 4.2.7 on 2024-02-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0002_remove_category_period_remove_category_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="color",
            field=models.CharField(max_length=6, null=True),
        ),
    ]
