# Generated by Django 4.2.7 on 2024-02-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0003_alter_category_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="color",
            field=models.CharField(max_length=7, null=True),
        ),
    ]
