# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    build: ./docker/database
    volumes:
    - ./docker/database/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    restart: always
    command: postgres -c client_encoding=UTF8 -c default_transaction_isolation="read committed" -c timezone=PST8
    environment:
      POSTGRES_PASSWORD: dev
    ports:
      - 15432:5432
  
  api-docs:
    image: redocly/redoc
    volumes:
     - ./docs/api:/usr/share/nginx/html/api
    restart: always
    environment:
      SPEC_URL: api/openapi.yaml
    ports:
      - 8080:80