# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    build: ./docker/database
    hostname: budget_nuggets_database
    volumes:
    - ./docker/database/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    restart: always
    command: postgres -c client_encoding=UTF8 -c default_transaction_isolation="read committed" -c timezone=PST8
    environment:
      POSTGRES_PASSWORD: dev
    ports:
      - 15432:5432
  
  # server:
  #   build: ./server
  #   volumes:
  #   - ./server:/server
  #   command: ./manage.py runserver 0.0.0.0:8000
  #   ports:
  #     - 8000:8000
  #   env_file: ./server/.env
  #   environment:
  #     - DATABASE_HOST=budget_nuggets_database
  #     - DATABASE_PORT=5432
  #   depends_on:
  #     - db

  
  api-docs:
    image: redocly/redoc
    volumes:
     - ./docs/api:/usr/share/nginx/html/api
    restart: always
    environment:
      SPEC_URL: api/openapi.yaml
    ports:
      - 8080:80