# Generated by Django 4.2.7 on 2024-02-04 05:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="budget_period",
            new_name="period",
        ),
    ]
