# Generated by Django 4.2.7 on 2023-12-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0003_alter_budgetusers_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="type",
            field=models.CharField(
                choices=[
                    ("AN", "Annual"),
                    ("MN", "Monthly"),
                    ("BW", "Biweekly"),
                    ("W", "Weekly"),
                    ("EV", "Event"),
                ],
                default="MN",
                max_length=2,
            ),
        ),
    ]
