# Generated by Django 4.2.7 on 2023-12-17 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budget", "0004_budget_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="name",
            field=models.CharField(default="A Budget"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="budget",
            name="owner",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budget_owner",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
