# Generated by Django 4.2.7 on 2024-01-30 06:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budget", "0005_budget_name_budget_owner"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BudgetPeriods",
            new_name="BudgetPeriod",
        ),
        migrations.RenameModel(
            old_name="BudgetUsers",
            new_name="BudgetUser",
        ),
    ]
