# Generated by Django 4.2.7 on 2024-01-30 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0007_budgetperiod_unique_budget_period"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField()),
                ("value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("color", models.CharField(max_length=6)),
                (
                    "budget_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budget.budgetperiod",
                    ),
                ),
            ],
        ),
    ]
