# Generated by Django 4.2.7 on 2024-01-31 01:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0008_budgetcategory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budgetcategory",
            name="budget_period",
        ),
        migrations.RemoveField(
            model_name="budgetperiod",
            name="budget",
        ),
    ]
