# Generated by Django 4.2.7 on 2024-01-31 01:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0005_alter_transaction_budget_period_and_more"),
        ("budget", "0009_remove_budgetcategory_budget_period_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BudgetCategory",
        ),
        migrations.DeleteModel(
            name="BudgetPeriod",
        ),
    ]
