# Generated by Django 4.2.4 on 2023-09-10 01:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="users",
            field=models.ManyToManyField(
                blank=True, through="accounts.AccountUser", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
