# Generated by Django 4.1.3 on 2023-03-13 06:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_accountuser_delete_role_alter_account_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="account_name",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="account",
            name="created",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
