# Generated by Django 4.1.3 on 2023-03-13 23:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_account_account_name_account_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="user",
        ),
        migrations.DeleteModel(
            name="AccountUser",
        ),
    ]
