# Generated by Django 4.2.7 on 2024-02-05 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0003_alter_category_color"),
        ("period", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="category.category",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="period.period"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="period",
            name="categories",
            field=models.ManyToManyField(
                through="period.PeriodCategory", to="category.category"
            ),
        ),
        migrations.AddConstraint(
            model_name="periodcategory",
            constraint=models.UniqueConstraint(
                fields=("category", "period"), name="category unique to period"
            ),
        ),
    ]
