openapi: "3.1.0"
servers:
  - url: "http://localhost:8000"
info:
  title: budget-nuggets api
  version: "1.0"
  license: { name: "none", url: "dh" }
components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: Authorization

paths:
  "/budgets":
    $ref: "budgets.yaml"
  "/transactions":
    $ref: "transactions.yaml"
