# Generated by Django 4.2.7 on 2024-01-30 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("budget", "0008_budgetcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("merchant", models.CharField()),
                ("notes", models.CharField()),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "budget_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budget.budgetperiod",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budget.budgetcategory",
                    ),
                ),
            ],
        ),
    ]
