# Generated by Django 4.2.7 on 2024-02-05 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0003_alter_category_color"),
        ("budget", "0001_initial"),
        ("period", "0002_periodcategory_period_categories_and_more"),
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="budget.budget"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="category.category",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="period.period"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="budget_period",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="category",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="budget",
        ),
        migrations.DeleteModel(
            name="TransactionCategory",
        ),
        migrations.AddField(
            model_name="transactionbudget",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="transaction.transaction",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="budget",
            field=models.ManyToManyField(
                through="transaction.TransactionBudget", to="budget.budget"
            ),
        ),
        migrations.AddConstraint(
            model_name="transactionbudget",
            constraint=models.UniqueConstraint(
                fields=("transaction", "budget", "period", "category"),
                name="unique transactions on budget",
            ),
        ),
    ]
