# Generated by Django 4.2.7 on 2024-03-01 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("period", "0002_periodcategory_period_categories_and_more"),
        ("budget", "0001_initial"),
        (
            "transaction",
            "0002_transactionbudget_remove_transaction_budget_period_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionPeriodCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "period_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="period.periodcategory",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="transaction",
            name="period",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="period.period",
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="budget",
        ),
        migrations.DeleteModel(
            name="TransactionBudget",
        ),
        migrations.AddField(
            model_name="transactionperiodcategory",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="transaction.transaction",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="period_categories",
            field=models.ManyToManyField(
                through="transaction.TransactionPeriodCategory",
                to="period.periodcategory",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="budget",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="budget.budget",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="transactionperiodcategory",
            constraint=models.UniqueConstraint(
                fields=("transaction", "period_category", "value"),
                name="unique transactions on period category",
            ),
        ),
    ]
