# Generated by Django 4.2.7 on 2024-03-04 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0003_transactionperiodcategory_transaction_period_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
