# Generated by Django 4.2.7 on 2024-01-30 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0008_budgetcategory"),
        ("transaction", "0003_transaction_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="budget",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="budget.budget",
            ),
            preserve_default=False,
        ),
    ]
